script: make

branches:
  only:
    - master
    - stable

matrix:
  allow_failures:
    - env: VISUAL_STUDIO=1

  include:
    - os: osx 
      language: c
      script: make
    
    - os: linux
      language: c
      script: make

    - os: windows
      language: c
      before_install: choco install make
      script: make

    - os: windows
      language: c
      env: VISUAL_STUDIO=1
      script:
        - cmd /c "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\devenv.exe" vctest/json_test.sln /Build