branches:
  only:
    - master
    - stable

matrix:
  include:
    - os: osx 
      language: c++
      compiler:
        - gcc
        - clang
      script: make unit_test
    
    - os: linux
      language: c++
      compiler: gcc
      script: make unit_test
    
    - os: linux
      language: c++
      compiler: clang
      script: make unit_test CC=clang

    - os: windows
      language: c
      compiler: gcc
      before_install: choco install make
      script: make

    - os: windows
      language: c
      compiler: clang
      before_install: choco install make
      script: make unit_test CC=clang

    - os: windows
      language: c
      script:
        - echo .travis\\build_vs2017.bat | cmd