script: make

branches:
  only:
    - master
    - stable

matrix:
  include:
    - os: osx 
      language: c
      script: make && make unit_test
    
    - os: linux
      language: c
      script: make && make unit_test

    - os: windows
      language: c
      before_install: choco install make
      script: make && make unit_test

    - os: windows
      language: c
      script:
        - echo .travis\\build_vs2017.bat | cmd